multilayer perceptron is the simplest type of ANN(artificial neural network).Each MLP model has an input layer ,output layer and hidden layers.The hidden layers are activated by activation functions like Relu,sigmoid,tanh,identity functions. These perceptrons in the layers are higly connected and parallel, this accelerates the computation

In [40]:
import pandas as pd
data=pd.read_csv('HR_comma_sep.csv')
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

preprocessing:Label encoding,map the salary column value:low:0,medium:1 and high:2.This is label encoding

In [41]:
#import label encoder
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
data['salary']=le.fit_transform(data['salary'])

In [42]:
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,1
1,0.80,0.86,5,262,6,0,1,0,sales,2
2,0.11,0.88,7,272,4,0,1,0,sales,2
3,0.72,0.87,5,223,5,0,1,0,sales,1
4,0.37,0.52,2,159,3,0,1,0,sales,1

In [43]:
#split the dataset
X=data[['salary','satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','Work_accident','promotion_last_5years']]
y=data['left']

In [44]:
#train test split function
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=30)

build employee churn using MLPclassifier

In [45]:
#import MLP classifier
from sklearn.neural_network import MLPClassifier

clf=MLPClassifier(hidden_layer_sizes=(6,5),random_state=30,verbose=True,learning_rate_init=0.01)
clf.fit(X_train,y_train)

Iteration 1, loss = 0.60793718
Iteration 2, loss = 0.54102947
Iteration 3, loss = 0.54279490
Iteration 4, loss = 0.53018527
Iteration 5, loss = 0.51728086
Iteration 6, loss = 0.50784278
Iteration 7, loss = 0.50229543
Iteration 8, loss = 0.49239825
Iteration 9, loss = 0.48371905
Iteration 10, loss = 0.47694937
Iteration 11, loss = 0.47127642
Iteration 12, loss = 0.47593535
Iteration 13, loss = 0.46977900
Iteration 14, loss = 0.46630921
Iteration 15, loss = 0.46098358
Iteration 16, loss = 0.45438067
Iteration 17, loss = 0.45493496
Iteration 18, loss = 0.45355310
Iteration 19, loss = 0.45317289
Iteration 20, loss = 0.45667700
Iteration 21, loss = 0.45390094
Iteration 22, loss = 0.45314887
Iteration 23, loss = 0.44912281
Iteration 24, loss = 0.45181862
Iteration 25, loss = 0.45543469
Iteration 26, loss = 0.45573433
Iteration 27, loss = 0.45174732
Iteration 28, loss = 0.44775173
Iteration 29, loss = 0.42846242
Iteration 30, loss = 0.40649764
Iteration 31, loss = 0.38555120
Iteration 32, loss = 0.37158232
Iteration 33, loss = 0.35114306
Iteration 34, loss = 0.33762627
Iteration 35, loss = 0.33083006
Iteration 36, loss = 0.30986387
Iteration 37, loss = 0.31497062
Iteration 38, loss = 0.30666914
Iteration 39, loss = 0.29141022
Iteration 40, loss = 0.30382316
Iteration 41, loss = 0.29725138
Iteration 42, loss = 0.28424302
Iteration 43, loss = 0.28475909
Iteration 44, loss = 0.28218429
Iteration 45, loss = 0.28190194
Iteration 46, loss = 0.27318043
Iteration 47, loss = 0.28110043
Iteration 48, loss = 0.27891045
Iteration 49, loss = 0.27406646
Iteration 50, loss = 0.27701076
Iteration 51, loss = 0.27261932
Iteration 52, loss = 0.28641999
Iteration 53, loss = 0.27579458
Iteration 54, loss = 0.26809915
Iteration 55, loss = 0.26963892
Iteration 56, loss = 0.27206147
Iteration 57, loss = 0.27671607
Iteration 58, loss = 0.27304174
Iteration 59, loss = 0.26623088
Iteration 60, loss = 0.26917718
Iteration 61, loss = 0.27045166
Iteration 62, loss = 0.26388552
Iteration 63, loss = 0.26404798
Iteration 64, loss = 0.26414127
Iteration 65, loss = 0.26205825
Iteration 66, loss = 0.26038162
Iteration 67, loss = 0.26085289
Iteration 68, loss = 0.25741236
Iteration 69, loss = 0.26441361
Iteration 70, loss = 0.25997393
Iteration 71, loss = 0.26117235
Iteration 72, loss = 0.25703548
Iteration 73, loss = 0.26290607
Iteration 74, loss = 0.27621962
Iteration 75, loss = 0.26312823
Iteration 76, loss = 0.26427619
Iteration 77, loss = 0.26079760
Iteration 78, loss = 0.25839277
Iteration 79, loss = 0.25715599
Iteration 80, loss = 0.26180199
Iteration 81, loss = 0.25571456
Iteration 82, loss = 0.25415496
Iteration 83, loss = 0.25270481
Iteration 84, loss = 0.25283093
Iteration 85, loss = 0.25563192
Iteration 86, loss = 0.24781378
Iteration 87, loss = 0.26090557
Iteration 88, loss = 0.25339538
Iteration 89, loss = 0.26842920
Iteration 90, loss = 0.25424747
Iteration 91, loss = 0.26548925
Iteration 92, loss = 0.27712359
Iteration 93, loss = 0.25869572
Iteration 94, loss = 0.25479368
Iteration 95, loss = 0.24797266
Iteration 96, loss = 0.24754935
Iteration 97, loss = 0.24579201
Iteration 98, loss = 0.24642796
Iteration 99, loss = 0.25400014
Iteration 100, loss = 0.25762363
Iteration 101, loss = 0.25457998
Iteration 102, loss = 0.24699146
Iteration 103, loss = 0.25230126
Iteration 104, loss = 0.25433302
Iteration 105, loss = 0.24806317
Iteration 106, loss = 0.26007042
Iteration 107, loss = 0.25251551
Iteration 108, loss = 0.24615337
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=30, verbose=True)

verbose:is used to print progress messages to standard ouptut
hidden_layer_sizes=(6, 5) 6 hidden layers with 5 neurons
learning_rate:step size
random_state=the initial random values for weights and for bias

In [46]:
#make prediciton
#and evaluate
y_pred=clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9017777777777778